language: node_js
node_js:
 - "node"
after_success:
 - git config --global user.name "bunthoeurndim"
 - git config --global user.email "bunthoeurndim@gmail.com"
 - git remote rm origin
 - git remote add origin https://bunthoeurndim:${GH_TOKEN}@github.com/react-continuous-deployment.git
 - npm run deploy