language: node_js
node_js:
 - "node"
after_success:
 - git config --global user.name "bunthoeurndim"
 - git config --global user.email "bunthoeurndim@gmail.com"
 - git remote rm origin
 - git remote add origin https://bunthoeurndim:${c8c9b298f794e1d39937159a77b28ab76999cac7}@github.com/bunthoeurndim/react-continuous-deployment.git
 - npm run deploy