language: node_js
node_js:
 - "node"
 deploy:
  provider: pages
  skip_cleanup: true
  github_token: "c8c9b298f794e1d39937159a77b28ab76999cac7" # Set in travis-ci.org dashboard
  on:
    branch: master